CREATE TABLE IF NOT EXISTS DomainControllerAffiliation (
  key                        VARCHAR(255) NOT NULL,
  attributesToSync           VARCHAR(255),
  bindPassword               VARCHAR(255),
  bindUser                   VARCHAR(255),
  highestCommittedUSN        BIGINT,
  invocationId               VARCHAR(255),
  rootDN                     VARCHAR(255),
  searchDeletedObjectsFilter VARCHAR(255),
  searchFilter               VARCHAR(255),
  syncBaseDN                 VARCHAR(255),
  url                        VARCHAR(255),
  PRIMARY KEY (key)
);

CREATE TABLE IF NOT EXISTS Employee (
  id         BIGINT generated BY DEFAULT AS IDENTITY,
  email      VARCHAR(255),
  ldapId     VARCHAR(255),
  name       VARCHAR(255),
  UNIQUE (email),
  PRIMARY KEY (id),
);
