package org.adsync4j.demo.jpa;

import org.adsync4j.demo.entity.DomainControllerAffiliation;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * A repository managing {@link DomainControllerAffiliation} entities. Implementation will be generated by
 * Spring Data JPA.
 */
@Repository
public interface DomainControllerAffiliationRepository extends JpaRepository<DomainControllerAffiliation, String> {
}
