package org.adsync4j.demo.jpa;

import org.adsync4j.demo.entity.DomainControllerAffiliation;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * A JPA repository managing {@link DomainControllerAffiliation} entities. The implementation is generated by Spring Data
 * JPA when the Spring context is initialized.
 */
@Repository
public interface DomainControllerAffiliationRepository extends JpaRepository<DomainControllerAffiliation, String> {
}
