package org.adsync4j.demo.jpa;

import org.adsync4j.demo.entity.Employee;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * A repository managing {@link Employee} entities. Implementation will be generated by Spring Data JPA.
 */
@Repository
public interface EmployeeRepository extends JpaRepository<Employee, Long> {

    Employee findByLdapId(String LdapId);
}
